# Define node version
FROM node:12.16.1-alpine as build
# Define container directory
WORKDIR /client
# Copy package*.json for npm install
# COPY package*.json ./client
# Run npm clean install, including dev dependencies for @angular-devkit
# RUN npm i
# Run npm install @angular/cli
# RUN npm install -g @angular/cli
# Copy all files
COPY ./client/dist ./
# Run ng build through npm to create dist folder
# RUN npm run build
# Define nginx for front-end server
FROM nginx:1.15.8-alpine
# Copy dist from ng build to nginx html folder
COPY --from=build /client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/
